DIALOG DLG_COLORMAPPING
{
    NAME IDS_POSTPROCESS_DIALOG; CENTER_V; CENTER_H; SCALE_V; SCALE_H;
    SCROLLGROUP { SCALE_V; SCALE_H; SCROLL_V; SCROLL_AUTO_V; GROUP { SCALE_H; SCALE_V; COLUMNS 1;

    GROUP
    {
        ALIGN_TOP; SCALE_H;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        CHECKBOX CORONA_DLG_POST_TONEMAPPING_ENABLE { NAME IDS_TONE_MAPPING_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 2;

            STATICTEXT { NAME IDS_EXPOSURE; CENTER_V; ALIGN_LEFT; SIZE 180, 0; }
            EDITNUMBERARROWS CORONA_DLG_POST_EXPOSURE { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_HIGHLIGHT_COMPRESSION; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_HIGHLIGHT_COMPRESSION { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_WHITE_BALANCE; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_WHITE_BALANCE { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_GREEN_MAGENTA_TINT; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_GREEN_MAGENTA_TINT { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_CONTRAST; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_CONTRAST { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_SATURATION; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_SATURATION { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_FILMIC_HIGHLIGHTS; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_FILMIC_HIGHLIGHTS { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_FILMIC_SHADOWS; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_FILMIC_SHADOWS { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_VIGNETTE_INTENSITY; CENTER_V; ALIGN_LEFT; SIZE 180, 0; }
            EDITNUMBERARROWS CORONA_DLG_POST_VIGNETTE_INTENSITY { CENTER_V; SCALE_H; }
        }
    }

    GROUP
    {
        ALIGN_TOP; SCALE_H;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        CHECKBOX CORONA_DLG_POST_LUT_ENABLE { NAME IDS_LUT_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 1;

            CORONALUTSELECTOR CORONA_DLG_POST_LUT_FILENAME { CENTER_V; SCALE_H; COMPACT; }

            GROUP
            {
                ALIGN_TOP; SCALE_H;
                BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
                COLUMNS 2;
                STATICTEXT { NAME IDS_LUT_OPACITY; CENTER_V; ALIGN_LEFT; }
                EDITNUMBERARROWS CORONA_DLG_POST_LUT_OPACITY { CENTER_V; SCALE_H; }
            }
        }
    }

    GROUP
    {
        ALIGN_TOP; SCALE_H;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        CHECKBOX CORONA_DLG_POST_BLOOM_ENABLE { NAME IDS_BLOOM_AND_GLARE_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 2;

            STATICTEXT { NAME IDS_BLOOM_INTENSITY; CENTER_V; ALIGN_LEFT; SIZE 180, 0; }
            EDITNUMBERARROWS CORONA_DLG_POST_BLOOM_INTENSITY { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_GLARE_INTENSITY; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_GLARE_INTENSITY { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_THRESHOLD; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_THRESHOLD { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_COLOR_INTENSITY; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_COLOR_INTENSITY { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_COLOR_SHIFT; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_COLOR_SHIFT { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_STREAK_COUNT; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_STREAK_COUNT { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_ROTATION; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_ROTATION { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_STREAK_BLUR; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_STREAK_BLUR { CENTER_V; SCALE_H; }
        }
    }

    GROUP
    {
        ALIGN_TOP; SCALE_H;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        CHECKBOX CORONA_DLG_POST_SHARPENING { NAME IDS_SHARPENING_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 2;

            STATICTEXT { NAME IDS_SHARPENING_AMOUNT; CENTER_V; ALIGN_LEFT; SIZE 180, 0; }
            EDITNUMBERARROWS CORONA_DLG_POST_SHARPENING_AMOUNT { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_SHARPENING_RADIUS; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_SHARPENING_RADIUS { CENTER_V; SCALE_H; }

            STATICTEXT { NAME IDS_BLURRING_RADIUS; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS CORONA_DLG_POST_BLURRING_RADIUS { CENTER_V; SCALE_H; }
        }
    }

    GROUP
    {
        ALIGN_TOP; SCALE_H;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        CHECKBOX CORONA_DLG_POST_DENOISING_ENABLE { NAME IDS_DENOISING_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 2;

            STATICTEXT { NAME IDS_DENOISING_AMOUNT; CENTER_V; ALIGN_LEFT; SIZE 180, 0; }
            EDITNUMBERARROWS CORONA_DLG_POST_DENOISING_AMOUNT { CENTER_V; SCALE_H; }
        }
    }

    GROUP
    {
        ALIGN_TOP; SCALE_H; SCALE_V;
        BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 6, 5, 1;
        COLUMNS 1;

        STATICTEXT { NAME IDS_INFO_SECTION; }
        SEPARATOR { SCALE_H; }

        GROUP
        {
            ALIGN_TOP; SCALE_H; SCALE_V;
            BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 1, 5, 1; 
            COLUMNS 1;

            MULTILINEEDIT CORONA_DLG_POST_INFO { SCALE_V; SCALE_H; WORDWRAP; READONLY; }
        }
    }
}}}
